kumuluzee:
  name: NakupovalniSeznami
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/nakupovalniseznam
      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznam
      username: postgres
      password: postgres
      max-pool-size: 20