kumuluzee:
  name: NakupovalniSeznami
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/uporabniki
#      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznam
      connection-url: jdbc:postgresql://192.168.99.100:35432/uporabniki
      username: postgres
      password: postgres
      max-pool-size: 20